# Generated by Django 3.0.1 on 2020-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_project_projectemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='employees.Client'),
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Project'),
        ),
    ]
