# Generated by Django 3.0.1 on 2020-03-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_client2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client2',
        ),
    ]
